### ISSUE TITLE
原理求助

### ISSUE THREAD

**Issue by MethodBoxAwA** [XeronOwO/QQBot4Sharp#1]
你好，请问一下QQbot（频道）是怎么获取AccessToken（鉴权）的啊，我直接请求它的官方接口会报invalid appid（
![9234dda80928613](https://github.com/XeronOwO/QQBot4Sharp/assets/135963417/798aca6e-ea47-408e-bf32-16d25e80a302)

**Comment by XeronOwO** [comment]
https://bot.q.qq.com/wiki/develop/api-v2/dev-prepare/interface-framework/api-use.html#%E9%89%B4%E6%9D%83%E6%96%B9%E5%BC%8F
官方的鉴权有关的说明在这里

https://github.com/XeronOwO/QQBot4Sharp/blob/master/QQBot4Sharp/Internal/BotContext.cs#L40
我的实现里面，这里给全局请求头添加了个X-Union-Appid参数，也就是我这个库发送的所有HTTP请求头都带这个参数（偷懒了下）
https://github.com/XeronOwO/QQBot4Sharp/blob/master/QQBot4Sharp/Internal/AccessTokenUpdater.cs#L29
这里是自动更新AccessToken的代码
https://github.com/XeronOwO/QQBot4Sharp/blob/master/QQBot4Sharp/Internal/BotContext.cs#L51
在更新后，还会给全局请求头添加了个Authorization参数

希望能够帮到你

**Comment by MethodBoxAwA** [comment]
感谢回复，我这边的问题是post（https://bots.qq.com/app/getAppAccessToken）这个接口时无法返回有效的access_token而是appid invalid。我的appid就是从QQ开放平台上复制的机器人的appid（）

**Comment by XeronOwO** [comment]
你这边post的是multipart/form-data还是application/json？我用的是后者，会不会是格式问题

**Comment by XeronOwO** [comment]
如果还是有问题的话，可以加一下官方开发者社区的频道问问
点击链接加入QQ频道【QQ开发者社区】：https://pd.qq.com/s/4cvh5xpfc

**Comment by MethodBoxAwA** [comment]
我用的是application/json
